version: '3'

services:
  server:
    build:
      context: server
      dockerfile: ../Dockerfile
    command: npm start
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@database:27017/${DATABASE_NAME}

  client:
    build:
      context: client
      dockerfile: ../Dockerfile
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./client
        target: /usr/app
      - /usr/app/node_modules
    depends_on:
      - server

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
