version: '3'

services:
  server:
    build:
      context: server
      dockerfile: ../Dockerfile
    command: npm run test
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chez_gustave"]
      interval: 5s
      timeout: 5s
      retries: 5